using System.Linq;
using Content.Client.Humanoid;
using Content.Shared._NF.Bank.Components;
using Content.Shared.Clothing;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Holds character data on the side of the setup GUI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CharacterPickerButton : ContainerButton
{
    /// <summary>
    /// Invoked if we should delete the attached character
    /// </summary>
    public event Action? OnDeletePressed;

    public CharacterPickerButton(
        IPrototypeManager prototypeManager,
        ISharedPlayerManager playerMan,
        ButtonGroup group,
<<<<<<< HEAD
        ICharacterProfile? profile,
        bool isSelected)
    {
        RobustXamlLoader.Load(this);
        

        _entManager = entityManager;
        AddStyleClass(StyleClassButton);
        ToggleMode = true;
        Group = group;
        var description = "Empty Slot";
        if (profile != null)
        {
            description = profile.Name;
            var query = IoCManager.Resolve<IEntityManager>().AllEntityQueryEnumerator<MoneyAccountsComponent>();
            var mone = 0;
            while (query.MoveNext(out var uid, out var grid))
            {
                grid.TryGetBalance(profile.Name, out mone);
            }
            if (profile is not HumanoidCharacterProfile humanoid)
            {
                _previewDummy = entityManager.SpawnEntity(prototypeManager.Index<SpeciesPrototype>(SharedHumanoidAppearanceSystem.DefaultSpecies).DollPrototype, MapCoordinates.Nullspace);
            }
            else
            {
                _previewDummy = UserInterfaceManager.GetUIController<LobbyUIController>()
                    .LoadProfileEntity(humanoid, null, true);

                var highPriorityJob = humanoid.JobPriorities.SingleOrDefault(p => p.Value == JobPriority.High).Key;
                if (highPriorityJob != default)
                {
                    var jobName = prototypeManager.Index(highPriorityJob).LocalizedName;
                    description = $"{description}\n{jobName}";
                    
                }
                description += $"\n${mone}";
            }
        }
        else
        {

=======
        HumanoidCharacterProfile profile,
        bool isSelected)
    {
        RobustXamlLoader.Load(this);
        AddStyleClass(StyleClassButton);
        ToggleMode = true;
        Group = group;
        var description = profile.Name;

        View.LoadPreview(profile);

        var highPriorityJob = profile.JobPriorities.SingleOrDefault(p => p.Value == JobPriority.High).Key;
        if (highPriorityJob != default)
        {
            var jobName = prototypeManager.Index(highPriorityJob).LocalizedName;
            description = $"{description}\n{jobName}";
>>>>>>> 6a675126ad848468cfce6f538545d77ed5e7fea9
        }

        Pressed = isSelected;
        DeleteButton.Visible = !isSelected && profile != null;

        DescriptionLabel.Text = description;

        ConfirmDeleteButton.OnPressed += _ =>
        {
            Parent?.RemoveChild(this);
            Parent?.RemoveChild(ConfirmDeleteButton);
            OnDeletePressed?.Invoke();
        };

        DeleteButton.OnPressed += _ =>
        {
            DeleteButton.Visible = false;
            ConfirmDeleteButton.Visible = true;
        };
    }
}
